typography_spectrum: 0.1360332197509706
color:
  brandStrength: 0.8334426824003458
  lightness: 0.8715210384689271
  saturation: 0.7528526068199426
  rhythmicContrast: 0.91134491446428
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.634625215549022
name: Elearning Laboratory
navigation: []
title: Better by design
